name: Update Content

on:
  push:
    paths:
      - 'content.json'

jobs:
  update-content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Récupérer tout l'historique du dépôt
      - name: Update HTML content
        run: |
          # Récupérer le contenu du fichier JSON
          content=$(cat content.json)
          
          # Mettre à jour le contenu HTML avec les nouvelles données
          IFS=$'\n' read -ra lines <<< "$content"
          for i in "${!lines[@]}"; do
            sed -i "$((i+2))s|<td contenteditable>.*</td>|<td contenteditable>${lines[$i]}</td>|" index.html
          done
          
          # Commiter et pousser les changements
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git add index.html
          git commit -m "Update content" || echo "Aucune modification à commiter."
          git push || echo "Impossible de pousser les changements."
