name: Update Content

on:
  push:
    paths:
      - 'content.json'

jobs:

  update-content:
    runs-on: ubuntu-latest
    
    # Attendre la fin du workflow "pages-build-deployment"
    needs: github-pages

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Récupérer tout l'historique du dépôt
      - name: Update HTML content
        run: |
          # Récupérer le contenu du fichier JSON
          content=$(cat content.json)
          
          # Mettre à jour le contenu HTML avec les nouvelles données
          IFS=$'\n' read -ra lines <<< "$content"
          for i in "${!lines[@]}"; do
            sed -i "$((i+2))s|<td contenteditable>.*</td>|<td contenteditable>${lines[$i]}</td>|" index.html
          done
          
          # Vérifier si des modifications ont été apportées
          if [[ -n $(git status --porcelain) ]]; then
            # Commiter et pousser les changements
            git add index.html
            git config user.name 'GitHub Actions'
            git config user.email 'actions@github.com'
            git commit -m "Update content"
            git push
          else
            echo "Aucune modification à commiter."
          fi

  # Workflow "pages-build-deployment"
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-pages-artifact@v1
      - uses: actions/deploy-pages@v1
